import {
  profile,
  user1,
  user2,
  user3,
  user4,
  user5,
  user6,
  user7,
  user8,
  user9,
  alexis,
  ella,
  freakbob,
  jane,
  kristie,
  leanne,
  livvy,
  marcus,
  paige,
  quandale,
  drake,
  littlejohn,
} from "../../assets/images";

export const userData = [
  {
    id: 1,
    name: "Janine",
    age: 18,
    hobbies: ["Concerts", "Festivals", "Photography"],
    bio: "Hey there! My name is Peggie. I'm a passionate fashion photographer with a love for capturing the beauty in everyday life. When I'm not behind the lens, you'll find me immersing myself in the energy of live music at concerts and festivals. Exploring new cultures and cuisines is my idea of a perfect adventure. Let's share stories over a cup of coffee and see where our shared passions take us!",
    distance: "3 miles away",
    imgPath: user1,
  },
  {
    id: 2,
    name: "Kristie",
    age: 20,
    hobbies: ["Hiking", "Cooking", "Music"],
    bio: "Hi there! I'm Diana, a nature lover who finds joy in the kitchen and the magic of music. Let's go on a hike and then cook up a storm together. Seeking someone to share adventures and good food with.",
    distance: "10 miles away",
    imgPath: user2,
  },
  {
    id: 3,
    name: "Sophie",
    age: 19,
    hobbies: ["Painting", "Yoga", "Traveling"],
    bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar. Let's embark on a journey of self-discovery together, exploring the world and creating masterpieces along the way.",
    distance: "2 miles away",
    imgPath: user3,
  },
  {
    id: 4,
    name: "Quandale",
    age: 22,
    hobbies: ["Soccer", "Cooking", "Movies"],
    bio: "Hi there! I'm Betty, a soccer lover who finds joy in the kitchen and the magic of movies. Let's kick a ball around and then cook up a storm together. Seeking someone to share adventures and good food with.",
    distance: "5 miles away",
    imgPath: user4,
  },
  {
    id: 5,
    name: "Leanna",
    age: 17,
    hobbies: ["Dancing", "Reading", "Hiking"],
    bio: "Hola! I'm Lily, a dance lover who finds joy in the rhythm of life. Books are my escape, and hiking fuels my spirit. Let's dance under the stars and get lost in stories over a cup of coffee. Eager to meet someone to share life's dance with.",
    distance: "7 miles away",
    imgPath: user5,
  },
  {
    id: 6,
    name: "Livvy",
    age: 21,
    hobbies: ["Singing", "Writing", "Sailing"],
    bio: "Ciao! I'm Chiara, a melody-maker who finds solace in writing and the serenity of sailing. Let's harmonize our voices and create music together. A poetic soul searching for someone to sail through life's highs and lows.",
    distance: "4 miles away",
    imgPath: user6,
  },
  {
    id: 7,
    name: "Emma",
    age: 18,
    hobbies: ["Singing", "Writing", "Sailing"],
    bio: "Hi there! I'm Emma, a melody-maker who finds solace in writing and the serenity of sailing. Let's harmonize our voices and create music together. A poetic soul searching for someone to sail through life's highs and lows.",
    distance: "4 miles away",
    imgPath: user7,
  },
  {
    id: 8,
    name: "Sarah",
    age: 23,
    hobbies: ["Surfing", "Gardening", "Painting"],
    bio: "Hi there! I'm Sarah, a surfer who finds joy in the garden and the magic of painting. Let's ride the waves and then paint up a storm together. Seeking someone to share adventures and good food with.",
    distance: "8 miles away",
    imgPath: user8,
  },
  {
    id: 9,
    name: "Freakbob",
    age: 25,
    hobbies: ["Yoga", "Hiking", "Photography"],
    bio: "Hello, I'm Olivia, a yoga enthusiast who finds peace in the serenity of nature and expression through photography. Let's go on a hike and then strike a pose together. Looking for someone to share adventures and good food with.",
    distance: "9 miles away",
    imgPath: user9,
  },
];

export const chatData = [
  {
    id: 1,
    name: "Little John",
    imgUrl: littlejohn,
    age: 18,
    isOnline: true,
    lastMessage:
      "ok bet",
    date: "2023-10-15",
    timeSent: "5 mins",
    chat: [
      {
        sender: "Little John",
        message: "hey",
        timestamp: "10:00 AM",
      },
      {
        sender: "Little John",
        message: "can i borrow some screws and galvanized square steel",
        timestamp: "10:05 AM",
      },
      {
        sender: "me",
        message: "for what",
        timestamp: "10:10 AM",
      },
      {
        sender: "Leanne",
        message: "so u can come live with me in my new house 😉",
        timestamp: "10:15 AM",
      },
      {
        sender: "me",
        message: "😳😳😳",
        timestamp: "10:20 AM",
      },
      {
        sender: "Leanne",
        message: "let's have a thousand babies",
        timestamp: "10:25 AM",
      },
      {
        sender: "me",
        message: "ok bet",
        timestamp: "10:26 AM",
      },
    ],
  },
  {
    id: 2,
    name: "Livvy",
    imgUrl: livvy,
    age: 21,
    isOnline: false,
    lastMessage: "sweet, see u there 😉",
    date: "2023-10-14",
    timeSent: "10 mins",
    chat: [
      {
        sender: "me",
        message: "hey",
        timestamp: "11:00 AM",
      },
      {
        sender: "me",
        message: "im baby gronk",
        timestamp: "11:05 AM",
      },
      {
        sender: "me",
        message: "u look really pretty by the way",
        timestamp: "11:10 AM",
      },
      {
        sender: "Livvy",
        message: "aww thank you!!",
        timestamp: "11:15 AM",
      },
      {
        sender: "me",
        message: "i have this party coming up on the 18th",
        timestamp: "11:20 AM",
      },
      {
        sender: "me",
        message: "it's called the tiktok rizz party",
        timestamp: "11:25 AM",
      },
      {
        sender: "me",
        message: "wanna join?",
        timestamp: "11:30 AM",
      },
      {
        sender: "Livvy",
        message: "im down",
        timestamp: "11:35 AM",
      },
      {
        sender: "me",
        message: "sweet, see u there 😉",
        timestamp: "11:40 AM",
      },
    ],
  },
  {
    id: 3,
    name: "Marcus",
    imgUrl: marcus,
    age: 16,
    isOnline: true,
    lastMessage: "I'm doing it, are you?",
    date: "2023-10-11",
    timeSent: "25 mins",
    chat: [
      {
        sender: "Marcus",
        message: "I'm doing it, are you?",
        timestamp: "2:35 PM",
      },
    ],
  },
  {
    id: 4,
    name: "Kristie",
    imgUrl: kristie,
    age: 19,
    isOnline: true,
    lastMessage: "i regret matching with you",
    date: "2023-10-10",
    timeSent: "30 mins",
    chat: [
      {
        sender: "me",
        message: "heh... what's cookin good lookin",
        timestamp: "3:00 PM",
      },

      {
        sender: "Kristie",
        message: "umm",
        timestamp: "3:05 PM",
      },
      {
        sender: "Kristie",
        message: "what",
        timestamp: "3:05 PM",
      },
      {
        sender: "me",
        message: "chat.. is this rizz?",
        timestamp: "3:10 PM",
      },
      {
        sender: "Kristie",
        message: "can u be normal for once",
        timestamp: "3:15 PM",
      },
      {
        sender: "me",
        message:
          "chat i just fumbled a baddie",
        timestamp: "3:20 PM",
      },
      {
        sender: "Kristie",
        message:
          "i regret matching with you",
        timestamp: "3:25 PM",
      },
    ],
  },

  {
    id: 5,
    name: "Jane",
    imgUrl: jane,
    age: 18,
    isOnline: false,
    lastMessage: "then it wasn't me",
    date: "2023-10-09",
    timeSent: "35 mins",
    chat: [
      {
        sender: "me",
        message: "u appeared in my dream last night",
        timestamp: "4:00 PM",
      },
      {
        sender: "Jane",
        message: "yoooo no way",
        timestamp: "4:05 PM",
      },      
      {
        sender: "Jane",
        message: "was my fit hard?",
        timestamp: "4:06 PM",
      },
      {
        sender: "me",
        message: "no not rlly",
        timestamp: "4:08 PM",
      },
      {
        sender: "Jane",
        message: "then it wasn't me",
        timestamp: "4:09 PM",
      },
    ],
  },
  {
    id: 6,
    name: "Freakbob",
    imgUrl: freakbob,
    age: 30,
    isOnline: true,
    lastMessage: "not today freakbob..",
    date: "2023-10-07",
    timeSent: "45 mins",
    chat: [
      {
        sender: "Freakbob",
        message: "yo can you pick up my calls",
        timestamp: "6:00 PM",
      },
      {
        sender: "me",
        message: "not today freakbob..",
        timestamp: "6:05 PM",
      },
    ],
  },
];

export const datesData = [
  {
    id: 1,
    imgUrl: kristie,
    name: "Kristie",
    lastName: "Jones",
    age: 19,
    city: "New York",
    country: "USA",
  },
  {
    id: 2,
    imgUrl: jane,
    name: "Jane",
    lastName: "Smith",
    age: 18,
    city: "Los Angeles",
    country: "USA",
  },
  {
    id: 3,
    imgUrl: quandale,
    name: "Quandale",
    lastName: "Dingle",
    age: 20,
    city: "London",
    country: "UK",
  },
  {
    id: 4,
    imgUrl: ella,
    name: "Ella",
    lastName: "Williams",
    age: 22,
    city: "Sydney",
    country: "Australia",
  },
  {
    id: 5,
    imgUrl: livvy,
    name: "Livvy",
    lastName: "Dunne",
    age: 21,
    city: "Paris",
    country: "France",
  },
  {
    id: 6,
    imgUrl: alexis,
    name: "Alexis",
    lastName: "Miller",
    age: 25,
    city: "Berlin",
    country: "Germany",
  },
  {
    id: 7,
    imgUrl: drake,
    name: "Drake",
    lastName: "Dunne",
    age: 27,
    city: "Toronto",
    country: "Canada",
  },
  {
    id: 8,
    imgUrl: paige,
    name: "Paige",
    lastName: "Moore",
    age: 19,
    city: "Tokyo",
    country: "Japan",
  },
  {
    id: 9,
    imgUrl: littlejohn,
    name: "Little John",
    lastName: "Taylor",
    age: 18,
    city: "Mumbai",
    country: "India",
  },
  {
    id: 10,
    imgUrl: freakbob,
    name: "Freakbob",
    lastName: "Anderson",
    age: 30,
    city: "Moscow",
    country: "Russia",
  },
];

export const profileData = [
  {
    name: "Jacob Jones",
    age: 30,
    imgUrl: profile,
    hobbies: ["Hiking", "Photography", "Cooking"],
    bio: "I'm an adventurous person who loves exploring new places, trying out different cuisines, capturing moments through photography, and spending time in nature. I enjoy hiking on weekends and experimenting with new recipes in the kitchen. Traveling and experiencing different cultures are some of my greatest passions, and I'm always looking for my next adventure.",
  },
];
